<!-- Copyright © Erickson Lopez. MIT License. -->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <RootNamespace>EricksonLopez.Concurrency.IntegrationTests</RootNamespace>
    <AssemblyName>EricksonLopez.Concurrency.IntegrationTests</AssemblyName>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <IsAotCompatible>false</IsAotCompatible>
    <EnableTrimAnalyzer>false</EnableTrimAnalyzer>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\EricksonLopez.Concurrency.Abstractions\EricksonLopez.Concurrency.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.Concurrency\EricksonLopez.Concurrency.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.Concurrency.Result\EricksonLopez.Concurrency.Result.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.Concurrency.Dapper\EricksonLopez.Concurrency.Dapper.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.Concurrency.PostgreSql\EricksonLopez.Concurrency.PostgreSql.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.Concurrency.Mediator\EricksonLopez.Concurrency.Mediator.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Dapper" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>

</Project>
