name: Feature Request
description: Suggest an idea or enhancement for EricksonLopez.Concurrency
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem or Use Case
      description: Is your feature request related to a problem or architectural use case?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution or public API design you would like to see.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Considered Alternatives
      description: Describe any alternative solutions or features you considered.
