// Copyright © Erickson Lopez. MIT License.
using System;
using System.Threading.Tasks;
using Dapper;
using EricksonLopez.Concurrency.Abstractions;
using EricksonLopez.Concurrency.Dapper;
using EricksonLopez.Concurrency.Result;
using EricksonLopez.Concurrency.Showcase.Models;
using Microsoft.Data.Sqlite;
using ResultInstance = EricksonLopez.Result.Result;

namespace EricksonLopez.Concurrency.Showcase.Levels;

/// <summary>
/// Level 04: Advanced Integration — Dapper Zero-Roundtrip execution, token updates, OptimisticUpdateBuilder, and functional Result monad mapping.
/// </summary>
public static class Level04_AdvancedIntegration
{
    public static async Task RunAsync()
    {
        Console.ForegroundColor = ConsoleColor.Cyan;
        Console.WriteLine("\n===============================================================================");
        Console.WriteLine(" LEVEL 04: ADVANCED INTEGRATION (DAPPER ZERO-ROUNDTRIP & RESULT MONAD MAPPING)");
        Console.WriteLine("===============================================================================");
        Console.ResetColor();

        // 1. Initialize SQLite in-memory database
        using var connection = new SqliteConnection("Data Source=:memory:");
        await connection.OpenAsync();

        // Create bank accounts and profiles table
        await connection.ExecuteAsync(@"
            CREATE TABLE bank_accounts (
                id TEXT PRIMARY KEY,
                owner TEXT NOT NULL,
                balance NUMERIC NOT NULL,
                version INTEGER NOT NULL
            );
            CREATE TABLE customer_profiles (
                id TEXT PRIMARY KEY,
                email TEXT NOT NULL,
                name TEXT NOT NULL,
                etag TEXT NOT NULL
            );
            INSERT INTO bank_accounts (id, owner, balance, version) VALUES ('ACC-2001', 'David Miller', 1500.00, 1);
            INSERT INTO customer_profiles (id, email, name, etag) VALUES ('CUST-100', 'david@example.com', 'David Miller', 'ETAG-INITIAL-1');
        ");

        Console.WriteLine("[1] In-memory SQLite initialized with bank account and customer profile records.");

        // 2. Generate SQL UPDATE query with OptimisticUpdateBuilder
        string updateSql = OptimisticUpdateBuilder.BuildVersionedUpdate(
            tableName: "bank_accounts",
            setClauses: "balance = @Balance",
            idColumn: "id",
            versionColumn: "version",
            idParam: "Id",
            versionParam: "ExpectedVersion");

        Console.WriteLine($"[2] SQL query generated by OptimisticUpdateBuilder:\n    {updateSql}");

        // 3. Execute optimistic update with Dapper (Success Case: ExpectedVersion = 1)
        Console.WriteLine("\n[3] Executing ExecuteOptimisticAsync with ExpectedVersion=1 (Success expected)...");
        var expectedSuccess = ExpectedVersion.Specific(1);

        ConcurrencyConflict? successConflict = await connection.ExecuteOptimisticAsync(
            sql: updateSql,
            param: new { Id = "ACC-2001", Balance = 1800.00m, ExpectedVersion = (long)expectedSuccess.Version },
            expectedVersion: expectedSuccess,
            entityId: "ACC-2001",
            entityType: "BankAccount");

        ResultInstance successResult = successConflict.ToResult();

        if (successResult.IsSuccess)
        {
            Console.ForegroundColor = ConsoleColor.Green;
            Console.WriteLine("    -> Update successful! Version automatically incremented to 2 in database.");
            Console.ResetColor();
        }

        // 4. Execute stale update (Conflict Case: ExpectedVersion = 1 when DB already has Version = 2)
        Console.WriteLine("\n[4] Executing ExecuteOptimisticAsync with ExpectedVersion=1 (when DB has Version=2)...");

        ConcurrencyConflict? detectedConflict = await connection.ExecuteOptimisticAsync(
            sql: updateSql,
            param: new { Id = "ACC-2001", Balance = 2000.00m, ExpectedVersion = (long)expectedSuccess.Version },
            expectedVersion: expectedSuccess,
            entityId: "ACC-2001",
            entityType: "BankAccount");

        if (detectedConflict is not null)
        {
            // 5. Functional monadic mapping to EricksonLopez.Result
            ResultInstance conflictResult = detectedConflict.ToResult();

            Console.ForegroundColor = ConsoleColor.Yellow;
            Console.WriteLine("    -> Conflict detected via Dapper (0 rows affected).");
            Console.WriteLine($"    -> Result.IsFailure: {conflictResult.IsFailure}");
            Console.WriteLine($"    -> Error Code:       {conflictResult.Error?.Code}");
            Console.WriteLine($"    -> Error Type:       {conflictResult.Error?.Type}");
            Console.WriteLine($"    -> Error Description:{conflictResult.Error?.Description}");
            Console.WriteLine($"    -> Retryability:     {conflictResult.Error?.Retryability}");
            Console.ResetColor();
        }

        // 6. Token-based Dapper execution: ExecuteOptimisticTokenAsync
        Console.WriteLine("\n[6] Executing ExecuteOptimisticTokenAsync for opaque ETag validation...");
        var expectedToken = ConcurrencyToken.From("ETAG-INITIAL-1");
        var nextToken = ConcurrencyToken.NewGuid();

        string tokenUpdateSql = @"
            UPDATE customer_profiles 
            SET email = @Email, name = @Name, etag = @NewToken 
            WHERE id = @Id AND etag = @ExpectedToken;";

        ConcurrencyConflict? tokenConflict = await connection.ExecuteOptimisticTokenAsync(
            sql: tokenUpdateSql,
            param: new { Id = "CUST-100", Email = "david.new@example.com", Name = "David Miller", NewToken = nextToken.Value, ExpectedToken = expectedToken.Value },
            expectedToken: expectedToken,
            entityId: "CUST-100",
            entityType: nameof(CustomerProfile));

        if (tokenConflict is null)
        {
            Console.ForegroundColor = ConsoleColor.Green;
            Console.WriteLine($"    -> Token update successful! New ETag set to '{nextToken.Value}'.");
            Console.ResetColor();
        }

        // 7. Evaluating row count outcomes with FromRowsAffected
        Console.WriteLine("\n[7] Evaluating raw row counts via ConcurrencyResultExtensions.FromRowsAffected:");
        var evaluatedResult = ConcurrencyResultExtensions.FromRowsAffected(0, "ACC-2001", nameof(BankAccount), ExpectedVersion.Specific(2));
        var evaluatedEntityResult = ConcurrencyResultExtensions.FromRowsAffected(1, new BankAccount("ACC-2001", "David Miller", 1800m, 2), "ACC-2001", ExpectedVersion.Specific(2));

        Console.WriteLine($"    - RowsAffected = 0 -> Result.IsFailure: {evaluatedResult.IsFailure}, Code: {evaluatedResult.Error?.Code}");
        Console.WriteLine($"    - RowsAffected = 1 -> Result.IsSuccess: {evaluatedEntityResult.IsSuccess}, Value: BankAccount '{evaluatedEntityResult.Value?.AccountId}'");
    }
}
